name: lint

on:
  pull_request:
    branches:
      - master
    paths:
      - 'mods/*.json'

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Retrieve list of modified files
        id: list-files
        run: |
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          echo "::set-output name=files::$FILES"

      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: -w ${{ steps.list-files.output.files }}
          only_changed: True
          dry: True
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
