name: lint

on:
  pull_request:
    branches:
      - master
    paths:
      - 'mods/*.json'

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Retrieve list of modified files
        id: list-files
        run: |
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=($(curl -s -X GET -G $URL | jq -r '.[] | .filename'))
          for f in ${FILES[@]}; do
            NFILES+="$(echo $f | awk '/mods\/.*\.json$/') "
          done
          echo "::set-output name=files::$NFILES"

      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: -w ${{ steps.list-files.output.files }}
          only_changed: True
          dry: True
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
