name: Scheduled prettifing

on:
  schedule:
    - cron: '15 2 * * 6'

jobs:
  prettify:
    name: Prettify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Pre-sanitize
        run: |
          echo "::group::JSON Files"
          for f in mods/*;
          do
            echo "- ${f}"
            jq '.' "${f}" 3>&1 1>/dev/null 2>&3-
          done
          echo "::endgroup::"

      - name: prettier
        run: npx prettier --write mods/*.json

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Create PR
        if: steps.git-check.outputs.modified == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'Scheduled prettier run.'
          committer: Github <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: 'prettier/patch'
          delete-branch: true
          title: '[Prettier] Scheduled weekly JSON fixup'
          body: |
            This pull request update several malformed JSON present in the repository.
            - - -
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            gh-actions
            prettier
